# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:45
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('summary', models.TextField(max_length=150, verbose_name='简介')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
